---
abstract: 'adjust prereqs to use latest version available'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-LatestPrereqs
requires:
  CPAN: 1.9402
  CPAN::Meta::Prereqs: 2.101670
  Dist::Zilla: 4.0
resources:
  repository: http://github.com/melo/dist-zilla-tools.git
version: 0.3
